export const TOOLBAR_MENU = {
  RIGHT_MENU: 'RIGHT_MENU',
  LEFT_MENU: 'LEFT_MENU'
}

export const LOADING_PROCCESS = {
  PROCCESS: "PROCCESS"
}

export const DIALOG = {
  LOGOUT: "LOGOUT",
  INFORMATION: "INFORMATION",
  PASSWORD: "PASSWORD",
}


